[tools]
hyperfine = "1.20.0"
jsonschema = "14.0.4"
node = "24.13.0"
yarn = "4.12.0"

[tasks."generate:schema"]
run = "node ./scripts/generate-schema.ts"
[tasks."generate:types"]
run = "node ./scripts/generate-types.ts"
[tasks.generate]
depends = ["generate:*"]

[tasks."test:schema"]
run = "jsonschema test schema/__tests__/*.test.json"
