[tools]
hyperfine = "1.20.0"
jsonschema = "12.10.1"
node = "24.12.0"
yarn = "4.12.0"

[settings.node]
# TODO remove at some point
gpg_verify = false

[tasks."generate:schema"]
run = "node ./scripts/generate-schema.ts"
[tasks."generate:types"]
run = "node ./scripts/generate-types.ts"
[tasks.generate]
depends = ["generate:*"]

[tasks."test:schema"]
run = "jsonschema test schema/__tests__/*.test.json"
